on: [push, pull_request]

name: Test-Suite beta ubuntu-20.04

jobs:
  CI-beta-ubuntu-20_04:
    uses: ./.github/workflows/reuse.yml
    with:
      toolchain: beta
      os: ubuntu-20.04
      packages: libvtk7.1p libvtk7-dev
      features: --features vtk7-0
