on: [push, pull_request]

name: Test-Suite beta ubuntu-20.04

jobs:
  CI-beta-ubuntu-20.04:
    uses: ./.github/workflows/reuse.yml
    with:
      toolchain: beta
      os: ubuntu-20.04
      features: --features vtk9-1
