on: [push, pull_request]

name: Test-Suite stable macos-16

jobs:
  CI-stable-macos-16:
    uses: ./.github/workflows/reuse.yml
    with:
      toolchain: stable
      os: macos-16
      packages: vtk
      environment_vars: 
