on: [push, pull_request]

name: Test-Suite stable ubuntu-20.04

jobs:
  CI-stable-ubuntu-20_04:
    uses: ./.github/workflows/reuse.yml
    with:
      toolchain: stable
      os: ubuntu-20.04
      packages: libvtk7 libvtk7-dev
      features: --features vtk7-0
