on: [push, pull_request]

name: Test-Suite stable ubuntu-20.04

jobs:
  CI-stable-ubuntu-20.04:
    uses: ./.github/workflows/reuse.yml
    with:
      toolchain: stable
      os: ubuntu-20.04
      features: --features vtk9-1
